language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql
  - DB=sqlite
  - DB=pgsql

matrix:
  include:
    - php: 5.4
      env:
        - DB=mysql PHPCOV=1

before_install:
  - git clone --depth 1 git://github.com/croogo/app -b master app
  - mkdir -p app/Vendor/cakephp app/Vendor/croogo
  - git clone --depth 1 git://github.com/cakephp/cakephp -b 2.7 app/Vendor/cakephp/cakephp
  - ln -s `pwd` app/Vendor/croogo/croogo
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.2' ] ; then git clone --depth 1 git://github.com/CakeDC/search -b master app/Plugin/Search ; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.2' ] ; then git clone --depth 1 git://github.com/CakeDC/migrations -b master app/Plugin/Migrations ; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.2' ] ; then git clone --depth 1 git://github.com/croogo/Ckeditor -b master app/Plugin/Ckeditor ; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then composer global require 'phpunit/phpunit=3.7.33'; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit app/Vendor/PHPUnit; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.3' ] ; then composer -n -vv install ; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.4' ] ; then composer -n -vv install ; fi"
  - for d in Plugin/* ; do if [ ! -f $app/$d ] ; then ln -s `pwd`/$d app/$d; fi ; done

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE croogo_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE croogo_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE SCHEMA croogo_test;' -U postgres -d croogo_test; fi"
  - cp app/Config/settings.json.install app/Config/settings.json
  - cp app/Config/croogo.php.install app/Config/croogo.php
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
    private \$identities = array(
      'mysql' => array(
        'datasource' => 'Database/Mysql',
        'host' => 'localhost',
        'login' => 'travis',
        'database' => 'croogo_test',
      ),
      'pgsql' => array(
        'datasource' => 'Database/Postgres',
        'host' => '127.0.0.1',
        'login' => 'postgres',
        'database' => 'croogo_test',
        'schema' => array(
          'default' => 'public',
          'test' => 'croogo_test',
        )
      ),
      'sqlite' => array(
        'datasource' => 'Database/Sqlite',
        'database' => array(
          'default' => ':memory:',
          'test' => ':memory:',
        ),
      )
    );
    public \$default = array(
      'persistent' => false,
      'host' => '',
      'login' => '',
      'password' => '',
      'database' => 'croogo',
      'prefix' => ''
    );
    public \$test = array(
      'persistent' => false,
      'host' => '',
      'login' => '',
      'password' => '',
      'database' => 'croogo_test',
      'prefix' => ''
    );
    public function __construct() {
      \$db = 'mysql';
      if (!empty(\$_SERVER['DB'])) {
        \$db = \$_SERVER['DB'];
      }
      foreach (array('default', 'test') as \$source) {
        \$config = array_merge(\$this->{\$source}, \$this->identities[\$db]);
        if (is_array(\$config['database'])) {
          \$config['database'] = \$config['database'][\$source];
        }
        if (!empty(\$config['schema']) && is_array(\$config['schema'])) {
          \$config['schema'] = \$config['schema'][\$source];
        }
        \$this->{\$source} = \$config;
      }
    }
    }" > app/Config/database.php

script:
  - sh -c "if [ '$PHPCOV' = '1' ]; then cd app && ./Console/cake test croogo CroogoTests --stderr --coverage-clover ../coverage.clover && cd .. && wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; else cd app && ./Console/cake test croogo CroogoTests --stderr ; fi"

notifications:
  email: false